version: '3.8'

services:
  db:
      image: postgres:14.3-alpine
      container_name: db
      restart: always
      environment:
        - POSTGRES_USER=psql_user
        - POSTGRES_PASSWORD=psql_pw
        - POSTGRES_DB=url-shortener
      ports:
        - 5432:5432
      volumes: 
        - db:/var/lib/postgresql/data
volumes:
    db:
      driver: local